import type {
  Project,
  WeatherEntry,
  SiteDiaryEntry,
  HindranceEntry,
  CustomerMilestoneEntry,
  ConstructionMilestoneEntry,
  WorkLaborEntry,
  DeptLaborEntry,
  MaterialReceiptEntry,
  SiteReport,
} from "./types"

export const projects: Project[] = [
  {
    id: "skyline-tower",
    name: "Skyline Tower",
    location: "Bandra Kurla Complex, Mumbai",
    startDate: "2024-01-15",
    status: "active",
  },
  {
    id: "green-valley",
    name: "Green Valley Residency",
    location: "Hinjewadi, Pune",
    startDate: "2024-03-01",
    status: "active",
  },
]

export const weatherEntries: Record<string, WeatherEntry[]> = {
  "skyline-tower": [
    {
      id: "w1",
      date: "2026-06-16",
      tempAt12PM: 34,
      rainStart: "14:30",
      rainEnd: "16:00",
      remarks: "Heavy showers, work suspended for 1.5 hrs",
    },
    {
      id: "w2",
      date: "2026-06-17",
      tempAt12PM: 32,
      rainStart: "",
      rainEnd: "",
      remarks: "Partly cloudy, no rain",
    },
    {
      id: "w3",
      date: "2026-06-18",
      tempAt12PM: 31,
      rainStart: "10:15",
      rainEnd: "11:00",
      remarks: "Light drizzle in morning, work resumed after break",
    },
  ],
  "green-valley": [
    {
      id: "w4",
      date: "2026-06-16",
      tempAt12PM: 29,
      rainStart: "",
      rainEnd: "",
      remarks: "Clear sky, good working conditions",
    },
    {
      id: "w5",
      date: "2026-06-17",
      tempAt12PM: 28,
      rainStart: "15:00",
      rainEnd: "15:45",
      remarks: "Brief shower, minor disruption",
    },
    {
      id: "w6",
      date: "2026-06-18",
      tempAt12PM: 30,
      rainStart: "",
      rainEnd: "",
      remarks: "Sunny, humid conditions",
    },
  ],
}

export const siteDiaryEntries: Record<string, SiteDiaryEntry[]> = {
  "skyline-tower": [
    {
      id: "sd1",
      srNo: 1,
      date: "2026-06-16",
      details: "Commenced slab formwork for Level 12. Reinforcement bars delivered and stacked at designated yard.",
      remarks: "Delivery delay of 2 hours due to traffic",
    },
    {
      id: "sd2",
      srNo: 2,
      date: "2026-06-17",
      details: "Reinforcement binding work for Level 12 slab in progress. 60% complete. Electrical conduits laid before pour.",
      remarks: "On schedule",
    },
    {
      id: "sd3",
      srNo: 3,
      date: "2026-06-18",
      details: "Concrete pouring for Level 12 slab completed. RMC from Ultratech, 3 transit mixers used. Curing compound applied.",
      remarks: "Poured 85 cum. Quality check passed.",
    },
  ],
  "green-valley": [
    {
      id: "sd4",
      srNo: 1,
      date: "2026-06-16",
      details: "Excavation for Block C foundation pit completed. Soil compaction underway.",
      remarks: "Excavation 100% complete",
    },
    {
      id: "sd5",
      srNo: 2,
      date: "2026-06-17",
      details: "PCC laid for Block C foundation. Anti-termite treatment completed for Block A ground floor.",
      remarks: "PCC thickness 100mm as per drawing",
    },
    {
      id: "sd6",
      srNo: 3,
      date: "2026-06-18",
      details: "Footing reinforcement for Block C columns started. Approved drawing issued by structural consultant.",
      remarks: "Drawing revision C received",
    },
  ],
}

export const hindranceEntries: Record<string, HindranceEntry[]> = {
  "skyline-tower": [
    {
      id: "h1",
      srNo: 1,
      date: "2026-06-10",
      hindranceDetails: "Non-availability of Tower Crane due to mechanical breakdown",
      itemsAffected: "Reinforcement bar lifting, Formwork material shifting",
      dateOfRecording: "2026-06-10",
      startDate: "2026-06-10",
      closureDate: "2026-06-12",
      totalPeriod: "3",
      overlappingPeriod: "0",
      netHindranceDays: "3",
      approvedBy: "R. Sharma",
      remarks: "Crane repair completed, work resumed",
    },
    {
      id: "h2",
      srNo: 2,
      date: "2026-06-16",
      hindranceDetails: "Heavy rainfall causing work stoppage",
      itemsAffected: "Concreting, Masonry work",
      dateOfRecording: "2026-06-16",
      startDate: "2026-06-16",
      closureDate: "2026-06-16",
      totalPeriod: "0.5",
      overlappingPeriod: "0",
      netHindranceDays: "0.5",
      approvedBy: "P. Mehta",
      remarks: "Half day loss",
    },
  ],
  "green-valley": [
    {
      id: "h3",
      srNo: 1,
      date: "2026-06-05",
      hindranceDetails: "Delay in approval of revised structural drawings",
      itemsAffected: "Foundation work for Block C",
      dateOfRecording: "2026-06-05",
      startDate: "2026-06-05",
      closureDate: "2026-06-17",
      totalPeriod: "13",
      overlappingPeriod: "2",
      netHindranceDays: "11",
      approvedBy: "V. Patil",
      remarks: "Drawings approved on 17th June",
    },
  ],
}

export const customerMilestoneEntries: Record<string, CustomerMilestoneEntry[]> = {
  "skyline-tower": [
    {
      id: "cm1",
      date: "2026-06-01",
      customerMilestone: "Completion of Structure up to Level 10",
      activity: "Slab concreting Level 10",
      workCompletedPercent: 100,
      contractor: "ABC Constructions Pvt Ltd",
    },
    {
      id: "cm2",
      date: "2026-06-18",
      customerMilestone: "Completion of Structure up to Level 12",
      activity: "Slab concreting Level 12",
      workCompletedPercent: 65,
      contractor: "ABC Constructions Pvt Ltd",
    },
    {
      id: "cm3",
      date: "2026-07-15",
      customerMilestone: "Completion of Structure up to Level 15",
      activity: "Column & Slab work Level 13-15",
      workCompletedPercent: 0,
      contractor: "ABC Constructions Pvt Ltd",
    },
  ],
  "green-valley": [
    {
      id: "cm4",
      date: "2026-06-30",
      customerMilestone: "Foundation completion Block A & B",
      activity: "Footing concreting Block A & B",
      workCompletedPercent: 100,
      contractor: "XYZ Infra Ltd",
    },
    {
      id: "cm5",
      date: "2026-07-31",
      customerMilestone: "Foundation completion Block C",
      activity: "Footing concreting Block C",
      workCompletedPercent: 20,
      contractor: "XYZ Infra Ltd",
    },
  ],
}

export const constructionMilestoneEntries: Record<string, ConstructionMilestoneEntry[]> = {
  "skyline-tower": [
    {
      id: "cons1",
      date: "2026-05-28",
      constructionMilestone: "Level 10 Slab Pour",
      activity: "Concrete pouring & curing",
      workCompletedPercent: 100,
      contractor: "ABC Constructions Pvt Ltd",
    },
    {
      id: "cons2",
      date: "2026-06-18",
      constructionMilestone: "Level 12 Slab Pour",
      activity: "Reinforcement, formwork, concreting",
      workCompletedPercent: 70,
      contractor: "ABC Constructions Pvt Ltd",
    },
    {
      id: "cons3",
      date: "2026-06-25",
      constructionMilestone: "Level 12 Column Casting",
      activity: "Column reinforcement & casting",
      workCompletedPercent: 0,
      contractor: "ABC Constructions Pvt Ltd",
    },
  ],
  "green-valley": [
    {
      id: "cons4",
      date: "2026-06-10",
      constructionMilestone: "Block A & B Foundation Complete",
      activity: "Footing concreting",
      workCompletedPercent: 100,
      contractor: "XYZ Infra Ltd",
    },
    {
      id: "cons5",
      date: "2026-06-18",
      constructionMilestone: "Block C Excavation Complete",
      activity: "Excavation & PCC",
      workCompletedPercent: 100,
      contractor: "XYZ Infra Ltd",
    },
  ],
}

export const workLaborEntries: Record<string, WorkLaborEntry[]> = {
  "skyline-tower": [
    {
      id: "wl1",
      date: "2026-06-18",
      milestone: "Level 12 Slab",
      activity: "Reinforcement Binding",
      workCompleted: "45",
      unit: "MT",
      contractor: "ABC Constructions Pvt Ltd",
      category: "Civil",
      noOfLabors: 28,
      remarks: "Binding wires issued from store",
    },
    {
      id: "wl2",
      date: "2026-06-18",
      milestone: "Level 12 Slab",
      activity: "Formwork Erection",
      workCompleted: "320",
      unit: "Sqm",
      contractor: "ABC Constructions Pvt Ltd",
      category: "Shuttering",
      noOfLabors: 15,
      remarks: "Plywood condition checked",
    },
    {
      id: "wl3",
      date: "2026-06-18",
      milestone: "Level 11 Columns",
      activity: "Masonry Block Work",
      workCompleted: "18",
      unit: "Sqm",
      contractor: "Shri Ganesh Masonry",
      category: "Masonry",
      noOfLabors: 12,
      remarks: "AAC blocks used",
    },
  ],
  "green-valley": [
    {
      id: "wl4",
      date: "2026-06-18",
      milestone: "Block C Foundation",
      activity: "Footing Reinforcement",
      workCompleted: "8",
      unit: "MT",
      contractor: "XYZ Infra Ltd",
      category: "Civil",
      noOfLabors: 18,
      remarks: "Fe500D bars",
    },
    {
      id: "wl5",
      date: "2026-06-18",
      milestone: "Block A Ground Floor",
      activity: "Column Casting",
      workCompleted: "6",
      unit: "Nos",
      contractor: "XYZ Infra Ltd",
      category: "Civil",
      noOfLabors: 10,
      remarks: "M30 grade concrete",
    },
  ],
}

export const deptLaborEntries: Record<string, DeptLaborEntry[]> = {
  "skyline-tower": [
    {
      id: "dl1",
      srNo: 1,
      date: "2026-06-17",
      challanNo: "CH-2026-0341",
      subContractorName: "Shivaji Labour Contractor",
      nameOfLabor: "Ramu Yadav",
      labourCategory: "Mason",
      noOfMandays: 1,
      workdoneDetails: "Brick masonry Level 11 south wall",
      approxQuantity: "12",
      unit: "Sqm",
      recoveryFrom: "Shivaji Labour Contractor",
      recoveryRate: "850",
      recoveryAmount: "850",
      authorisedBy: "P. Desai",
      debitDetails: "Debit to subcontractor account",
      remarks: "Work satisfactory",
    },
    {
      id: "dl2",
      srNo: 2,
      date: "2026-06-18",
      challanNo: "CH-2026-0342",
      subContractorName: "Mahesh Carpenter Works",
      nameOfLabor: "Suresh Teli",
      labourCategory: "Carpenter",
      noOfMandays: 1,
      workdoneDetails: "Formwork fabrication for Level 12 beam",
      approxQuantity: "24",
      unit: "Rmt",
      recoveryFrom: "Mahesh Carpenter Works",
      recoveryRate: "950",
      recoveryAmount: "950",
      authorisedBy: "R. Sharma",
      debitDetails: "Debit to subcontractor account",
      remarks: "Extra work, need approval",
    },
  ],
  "green-valley": [
    {
      id: "dl3",
      srNo: 1,
      date: "2026-06-18",
      challanNo: "CH-GV-0118",
      subContractorName: "Pune Labour Supply",
      nameOfLabor: "Ganesh Bhosale",
      labourCategory: "Helper",
      noOfMandays: 1,
      workdoneDetails: "Earth filling and compaction around Block B footing",
      approxQuantity: "15",
      unit: "Cum",
      recoveryFrom: "Pune Labour Supply",
      recoveryRate: "600",
      recoveryAmount: "600",
      authorisedBy: "V. Patil",
      debitDetails: "Debit to subcontractor account",
      remarks: "",
    },
  ],
}

export const materialReceiptEntries: Record<string, MaterialReceiptEntry[]> = {
  "skyline-tower": [
    {
      id: "mr1",
      srNo: 1,
      date: "2026-06-16",
      timeIn: "08:30",
      poNo: "PO-2026-0078",
      grnNo: "GRN-0341",
      materialDescription: "TMT Steel Bars Fe500D 12mm dia",
      unit: "MT",
      supplier: "SAIL Steel Depot",
      quantityReceived: 12.5,
      quantityRejected: 0.5,
      quantityAccepted: 12,
      remarks: "0.5 MT rejected due to surface rust",
    },
    {
      id: "mr2",
      srNo: 2,
      date: "2026-06-17",
      timeIn: "10:00",
      poNo: "PO-2026-0079",
      grnNo: "GRN-0342",
      materialDescription: "Cement OPC 53 Grade (50kg bags)",
      unit: "Bags",
      supplier: "Ultratech Cement",
      quantityReceived: 500,
      quantityRejected: 10,
      quantityAccepted: 490,
      remarks: "10 bags damaged in transit",
    },
    {
      id: "mr3",
      srNo: 3,
      date: "2026-06-18",
      timeIn: "07:45",
      poNo: "PO-2026-0080",
      grnNo: "GRN-0343",
      materialDescription: "AAC Blocks 600x200x150mm",
      unit: "Cum",
      supplier: "Aerocon Blocks",
      quantityReceived: 25,
      quantityRejected: 0,
      quantityAccepted: 25,
      remarks: "All accepted, stacked at Block B yard",
    },
  ],
  "green-valley": [
    {
      id: "mr4",
      srNo: 1,
      date: "2026-06-16",
      timeIn: "09:00",
      poNo: "PO-GV-0041",
      grnNo: "GRN-GV-0201",
      materialDescription: "TMT Steel Bars Fe500D 16mm dia",
      unit: "MT",
      supplier: "JSW Steel",
      quantityReceived: 8,
      quantityRejected: 0,
      quantityAccepted: 8,
      remarks: "Test certificates received",
    },
    {
      id: "mr5",
      srNo: 2,
      date: "2026-06-18",
      timeIn: "11:30",
      poNo: "PO-GV-0042",
      grnNo: "GRN-GV-0202",
      materialDescription: "Crushed Stone Aggregate 20mm",
      unit: "Cum",
      supplier: "Pune Aggregates Pvt Ltd",
      quantityReceived: 30,
      quantityRejected: 2,
      quantityAccepted: 28,
      remarks: "2 cum rejected - excess fines",
    },
  ],
}

export const siteReports: SiteReport[] = [
  {
    id: "sr1",
    projectId: "skyline-tower",
    date: "2026-06-18",
    rainFrom: "10:15",
    rainTo: "11:00",
    workItems: [
      { id: "wi1", itemNo: "1", description: "Reinforcement Binding – Level 12 Slab", carpenter: 0, fitter: 8, helper: 10, mason: 0, skilled: 5, unskilled: 5 },
      { id: "wi2", itemNo: "2", description: "Formwork Erection – Level 12 Slab", carpenter: 12, fitter: 0, helper: 8, mason: 0, skilled: 0, unskilled: 4 },
      { id: "wi3", itemNo: "3", description: "Block Masonry – Level 11", carpenter: 0, fitter: 0, helper: 6, mason: 6, skilled: 0, unskilled: 0 },
    ],
    remarks: "Shortage of binding wire. Additional plywood required for formwork by tomorrow.",
    rmcPreviousReceipt: "1250",
    rmcTodaysReceipt: "85",
    rmcCumulativeReceipt: "1335",
    rmcOpeningBalance: "45",
    rmcTodaysConsumption: "85",
    rmcClosingBalance: "45",
    reinfPreviousReceipt: "185",
    reinfTodaysReceipt: "12",
    reinfCumulativeReceipt: "197",
    reinfOpeningBalance: "22",
    reinfTodaysConsumption: "15",
    reinfClosingBalance: "19",
    decisionsPending: "1. Approval needed for additional column starter bars at Level 12.\n2. Clarification on beam depth at Grid C-4 pending from structural consultant.",
    milestonesAchieved: "Level 12 slab reinforcement 65% complete. On track for pour on 20th June.",
    materialReceiptReport: [
      { id: "mrr1", itemNo: "1", materialDescription: "TMT Bars 12mm", unit: "MT", supplierName: "SAIL Steel", challanNo: "CH-341", previous: 185, today: 12, cumulative: 197 },
      { id: "mrr2", itemNo: "2", materialDescription: "Cement OPC 53", unit: "Bags", supplierName: "Ultratech", challanNo: "DC-890", previous: 4200, today: 490, cumulative: 4690 },
    ],
    siteVisitors: "1. Mr. Arun Khanna – Client representative, inspection of Level 12 progress\n2. Mr. Sunil Joshi – Structural Consultant, beam reinforcement review",
    preparedBy: "Rakesh Desai",
    siteIncharge: "Pradeep Mehta",
  },
  {
    id: "sr2",
    projectId: "skyline-tower",
    date: "2026-06-17",
    rainFrom: "",
    rainTo: "",
    workItems: [
      { id: "wi4", itemNo: "1", description: "Reinforcement Binding – Level 12 Slab", carpenter: 0, fitter: 8, helper: 10, mason: 0, skilled: 5, unskilled: 5 },
      { id: "wi5", itemNo: "2", description: "Formwork Erection – Level 12 Slab", carpenter: 12, fitter: 0, helper: 8, mason: 0, skilled: 0, unskilled: 4 },
    ],
    remarks: "No major shortfalls.",
    rmcPreviousReceipt: "1250",
    rmcTodaysReceipt: "0",
    rmcCumulativeReceipt: "1250",
    rmcOpeningBalance: "45",
    rmcTodaysConsumption: "0",
    rmcClosingBalance: "45",
    reinfPreviousReceipt: "173",
    reinfTodaysReceipt: "12",
    reinfCumulativeReceipt: "185",
    reinfOpeningBalance: "10",
    reinfTodaysConsumption: "0",
    reinfClosingBalance: "22",
    decisionsPending: "Approval for starter bars pending.",
    milestonesAchieved: "Formwork 50% complete for Level 12.",
    materialReceiptReport: [
      { id: "mrr3", itemNo: "1", materialDescription: "TMT Bars 12mm", unit: "MT", supplierName: "SAIL Steel", challanNo: "CH-340", previous: 173, today: 12, cumulative: 185 },
    ],
    siteVisitors: "None",
    preparedBy: "Rakesh Desai",
    siteIncharge: "Pradeep Mehta",
  },
  {
    id: "sr3",
    projectId: "green-valley",
    date: "2026-06-18",
    rainFrom: "",
    rainTo: "",
    workItems: [
      { id: "wi6", itemNo: "1", description: "Footing Reinforcement – Block C", carpenter: 0, fitter: 6, helper: 8, mason: 0, skilled: 4, unskilled: 0 },
      { id: "wi7", itemNo: "2", description: "Column Casting – Block A Ground Floor", carpenter: 4, fitter: 4, helper: 6, mason: 0, skilled: 0, unskilled: 4 },
    ],
    remarks: "Need more aggregate for column casting tomorrow.",
    rmcPreviousReceipt: "380",
    rmcTodaysReceipt: "24",
    rmcCumulativeReceipt: "404",
    rmcOpeningBalance: "12",
    rmcTodaysConsumption: "18",
    rmcClosingBalance: "18",
    reinfPreviousReceipt: "62",
    reinfTodaysReceipt: "8",
    reinfCumulativeReceipt: "70",
    reinfOpeningBalance: "8",
    reinfTodaysConsumption: "6",
    reinfClosingBalance: "12",
    decisionsPending: "1. Revised drawing for Block C columns awaited.\n2. Approval for aggregate supplier change pending.",
    milestonesAchieved: "Block C excavation and PCC complete. Block A column casting started.",
    materialReceiptReport: [
      { id: "mrr4", itemNo: "1", materialDescription: "TMT Bars 16mm", unit: "MT", supplierName: "JSW Steel", challanNo: "CH-GV-118", previous: 62, today: 8, cumulative: 70 },
      { id: "mrr5", itemNo: "2", materialDescription: "Aggregate 20mm", unit: "Cum", supplierName: "Pune Aggregates", challanNo: "CH-PA-45", previous: 180, today: 28, cumulative: 208 },
    ],
    siteVisitors: "1. Mr. Nitin Kulkarni – PMC Engineer, routine inspection",
    preparedBy: "Satish Borse",
    siteIncharge: "Vijay Patil",
  },
]
